apiVersion: v1
kind: ServiceAccount
metadata:
metadata:
  name: {{ include "zfs-localpv.nodeServiceAccountName" . }}
imagePullSecrets:
  {{- toYaml .Values.imagePullSecrets | nindent 2 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "zfs-localpv.fullname" . }}-driver-registrar-role
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumes", "nodes", "services"]
    verbs: ["get", "list"]
  - apiGroups: ["*"]
    resources: ["zfsvolumes", "zfssnapshots"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "zfs-localpv.fullname" . }}-driver-registrar-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "zfs-localpv.nodeServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "zfs-localpv.fullname" . }}-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io
---
